spring.application.name=todosimple

# Configuracoess de Conexao com o MariaDB
spring.datasource.url=jdbc:mysql://localhost:3306/todosimple
spring.datasource.username=aluno
spring.datasource.password=Renan12@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# configuracao  do H2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracoes do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect